[build]
  command = "npx convex deploy && pnpm run build"
  publish = "build/client"
  
[build.environment]
  NODE_VERSION = "20.15.1"
  NPM_FLAGS = "--version"

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200