[build]
  command = "pnpm run build"
  publish = "build/client"
  
[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_FLAGS = "--version"

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200