[build]
  command = "npx convex deploy && pnpm run build"
  publish = "build/client"
  
[build.environment]
  NODE_VERSION = "20.15.1"
  NPM_FLAGS = "--version"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  included_files = ["functions/**"]
  external_node_modules = ["@remix-run/cloudflare"]
  node_bundler = "esbuild"