[build]
  command = "pnpm install && npx convex deploy && pnpm run build"
  publish = "build/client"
  
[build.environment]
  NODE_VERSION = "20.15.1"
  NPM_VERSION = "10.2.4"
  PNPM_VERSION = "8.15.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "build/server"
  node_bundler = "esbuild"

[dev]
  framework = "remix"
  targetPort = 5173

[build.processing]
  skip_processing = false