[build]
  command = "npx convex deploy && pnpm run build"
  publish = "build/client"
  
[build.environment]
  NODE_VERSION = "20.15.1"
  NPM_VERSION = "10.2.4"
  PNPM_VERSION = "8.15.1"
  VITE_GITHUB_CLIENT_ID = "Ov23liA3PwvOtkwYOKUy"
  VITE_CONVEX_URL = "https://judicious-pelican-858.convex.cloud"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    "X-Frame-Options" = "DENY"
    "X-XSS-Protection" = "1; mode=block"

[dev]
  framework = "remix"
  targetPort = 5173

[build.processing]
  skip_processing = false