[build]
  command = "npx pnpm install --store=node_modules/.pnpm-store && pnpm run build"
  publish = "build/client"
  functions = "build/server"

[dev]
  command = "pnpm run dev"
  port = 5173
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_FLAGS = "--version"
  PNPM_FLAGS = "--shamefully-hoist --store=node_modules/.pnpm-store" 