name = "scriptot"
compatibility_date = "2025-02-14"

[build]
command = "pnpm run build"

[site]
bucket = "./build/client"

[vars]
VITE_GITHUB_CLIENT_ID = "Ov23liA3PwvOtkwYOKUy"
GITHUB_CLIENT_SECRET = "61a825cbffabe464cc8b5eca1d5a22ac211687bc"
VITE_CONVEX_URL = "https://judicious-pelican-858.convex.cloud"
VITE_APP_URL = "https://scriptot.pages.dev"