#:schema node_modules/wrangler/config-schema.json
name = "scriptot"
compatibility_date = "2024-02-17"
nodejs_compat = true

[build]
command = "pnpm run build"
pages_build_output_dir = "build/client"

[site]
bucket = "./build/client"
