name = "codeiq"
compatibility_date = "2024-01-01"

# Remove build.output_dir and use pages_build_output_dir instead
pages_build_output_dir = "build/client"

[site]
bucket = "./build/client"

# Add main field as suggested
main = "functions/[[path]].ts"