name = "scriptot"
main = "dist/index.js"
compatibility_date = "2025-02-14"

[build]
command = "pnpm run build"
[build.upload]
format = "service-worker"

[env.production]
# account_id = "your_account_id"
# zone_id = "your_zone_id"
# workers_dev = true
# route = "https://codeiq-a4u.pages.dev/*"
