name = "scriptot"
compatibility_date = "2025-02-14"

main = "build/server/index.js"

[build]
command = "pnpm run build"

[site]
bucket = "./build/client"

[vars]
VITE_GITHUB_CLIENT_ID = "Ov23liNA1dVBglJhaSw5"
VITE_CONVEX_URL = "https://judicious-pelican-858.convex.cloud"
VITE_APP_URL = "https://scriptot.pages.dev"